name: CI CALCULADORA C++
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_and_test:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install CppUnit
      run: sudo apt install -y libcppunit-dev
    - name: makefile
      run: make
    - name: makefile tests
      run: make tests
